name: context variables demo
on: 
  workflow_dispatch:
jobs: 
  context_demo: 
    runs-on: ubuntu-latest
    steps:
      - name: use context variables
        run: |
          echo "This workflow is trigerred by ${{ github.actor }}"
          echo "This repo name is ${{ github.repository }}"
          echo "Thos workflow even is trigerred by ${{  github.event_name}}"
            
