name: Workflow Demo
on: 
  push:
    branches: 
      - main
      - develop
      - 'release/*'
  pull_request:
    types: 
      - opened
    branches: main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Build Step
        run: |
        echo "this is the build step"
        echo "Hello my city is ${{vars.MY_CITY}}"
      
